<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFhyxMX7\Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFhyxMX7/Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFhyxMX7.legacy');

    return;
}

if (!\class_exists(Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFhyxMX7\Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, false);
}

return new \ContainerFhyxMX7\Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer([
    'container.build_hash' => 'FhyxMX7',
    'container.build_id' => '7c1579ed',
    'container.build_time' => 1672130109,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFhyxMX7');
