doctrine:
    dbal: { connections: { default: { host: localhost, port: 3306, user: natasha, password: password, dbname: main_project_database, mapping_types: { enum: string, bit: boolean }, server_version: 8.0.31-0ubuntu0.20.04.2 } } }
