<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTvtneyb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTvtneyb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTvtneyb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTvtneyb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTvtneyb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tvtneyb',
    'container.build_id' => '14680d90',
    'container.build_time' => 1673248947,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTvtneyb');
