<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerXJU42Hj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXJU42Hj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXJU42Hj.legacy');
=======
if (\class_exists(\ContainerTvtneyb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTvtneyb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTvtneyb.legacy');
>>>>>>> f0beae0317f21adfda97912d29dff73daa4f153f

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerXJU42Hj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXJU42Hj\App_KernelDevDebugContainer([
    'container.build_hash' => 'XJU42Hj',
    'container.build_id' => '9d37e4e5',
    'container.build_time' => 1673261032,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXJU42Hj');
=======
    \class_alias(\ContainerTvtneyb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTvtneyb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tvtneyb',
    'container.build_id' => '14680d90',
    'container.build_time' => 1673248947,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTvtneyb');
>>>>>>> f0beae0317f21adfda97912d29dff73daa4f153f
