<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXyJiKwW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXyJiKwW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXyJiKwW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXyJiKwW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXyJiKwW\App_KernelDevDebugContainer([
    'container.build_hash' => 'XyJiKwW',
    'container.build_id' => '4f58b3be',
    'container.build_time' => 1673891452,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXyJiKwW');
